name: dna-sufo
channels:
  - conda-forge
  - pytorch
dependencies:
  - python
  - pytorch
  - pip
  - skimage
  - matplotlib
  - pandas
  - pytables
  - pip:
    - cellpose
    - trackpy
    - gitpython