name: dnasufo
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python
  - pytorch-cuda=12.4
  - torchvision
  - pip
  - scikit-image
  - matplotlib
  - pandas
  - pytables
  - h5py
  - tifffile
  - pip:
    - cellpose
    - trackpy